# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 442eba3a8593900d8cfb3b02746bb984190681a5a0a327aa6a21e3ca7638984f12dd1958abf63dfb623608e9f8f7a62fd108e847e81de3223781383a848ccb04

test:
  secret_key_base: b0d01ee2ea9167394afdc47c37ca8b4219d4517ca0cf93b17f44d31eddcebe9276dcd767c6c32223b995dc93aa4cd8a698febde01ef4b79a2ad7baca13b20e23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
